# TARA Ocean Miocrobiome Visualisation

### Instructions on running the analysis as below-

Please ensure you havfe installed the required packages and dependencies as mentioned in the 'importing required libraries section'.

Data used was being provided by Department of School of Computing at Newcastle University for module in Complex Data Visualisation for Ms. Data science course however it is a public dataset and can be obtained from the website- https://fondationtaraocean.org/en/expedition/tara-oceans/.

Change the filepath to your local path where datafiles are stored and then can run the code as below.

In [1]:
# importing required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import plotly.express as px
from jupyter_dash import JupyterDash 
import dash 
from dash import dcc 
from dash import html
from dash.dependencies import Input, Output

## Taxonomy-wise Abundance

In [2]:
# Reading taxonomy table
taxonomy= pd.read_csv('C:/Users/Aditi Sony/Downloads/Complex Data Visualisation/Summative Assignment/Data/Tara_OTUtableTax.csv')
taxonomy.head()

,Domain,Phylum,Class,Order,Family,Genus,OTU.rep,TARA_018_DCM_0.22-1.6,TARA_018_SRF_0.22-1.6,TARA_023_DCM_0.22-1.6,...,TARA_085_MES_0.22-3,TARA_085_SRF_0.22-3,TARA_093_DCM_0.22-3,TARA_093_SRF_0.22-3,TARA_094_SRF_0.22-3,TARA_096_SRF_0.22-3,TARA_098_DCM_0.22-3,TARA_098_MES_0.22-3,TARA_098_SRF_0.22-3,TARA_099_SRF_0.22-3
0,Bacteria,Proteobacteria,Gammaproteobacteria,Enterobacteriales,Enterobacteriaceae,Enterobacter,AAAA02020713.1.1297,0.000000,0.00000,0.0,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000
1,Bacteria,Proteobacteria,Gammaproteobacteria,B38,Gammaproteobacteria(undef),Gammaproteobacteria(undef),AAAA02020732.66.1490,0.000000,0.00000,0.0,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000
2,Bacteria,Proteobacteria,Gammaproteobacteria,Enterobacteriales,Enterobacteriaceae,Enterobacter,AAAA02029623.1.1373,0.000000,0.00000,0.0,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.000000
3,Bacteria,Verrucomicrobia,Opitutae,Puniceicoccales,Puniceicoccaceae,Opitutae(undef),AACY020016122.205.1491,0.000000,0.00000,0.0,...,0.0,0.0,0.001609,0.0,0.000783,0.002924,0.0,0.0,0.0,0.002082
4,Bacteria,Proteobacteria,Gammaproteobacteria,Alteromonadales,Alteromonadaceae,BD1-7 clade,AACY020061762.7.1504,0.002588,0.00449,0.0,...,0.0,0.0,0.001609,0.0,0.002348,0.000000,0.0,0.0,0.0,0.000000

### Highest abundance Domain?

In [3]:
Domain_group = taxonomy.groupby('Domain').sum()
Domain_group['Percent']= Domain_group.sum(axis=1, numeric_only=True) / 139
Domain_group.reset_index(inplace=True)
Domain_group = Domain_group.rename(columns = {'index':'Domain'})

In [4]:
Domain_group.head()

,Domain,TARA_018_DCM_0.22-1.6,TARA_018_SRF_0.22-1.6,TARA_023_DCM_0.22-1.6,TARA_023_SRF_0.22-1.6,TARA_025_DCM_0.22-1.6,TARA_025_SRF_0.22-1.6,TARA_030_DCM_0.22-1.6,TARA_030_SRF_0.22-1.6,TARA_031_SRF_0.22-1.6,...,TARA_085_SRF_0.22-3,TARA_093_DCM_0.22-3,TARA_093_SRF_0.22-3,TARA_094_SRF_0.22-3,TARA_096_SRF_0.22-3,TARA_098_DCM_0.22-3,TARA_098_MES_0.22-3,TARA_098_SRF_0.22-3,TARA_099_SRF_0.22-3,Percent
0,Archaea,2.841492,2.584517,1.780197,0.491446,2.91150,0.052538,0.076020,0.017766,1.982837,...,0.003676,0.017697,0.006730,0.041482,0.391819,2.530068,19.772825,1.056533,1.053442,6.217784
1,Bacteria,92.758249,93.439189,94.197875,95.838106,92.26936,96.959576,95.458433,96.474031,94.959420,...,95.848421,98.774105,99.081365,98.129378,96.611062,90.863263,71.419896,96.043533,96.070410,88.327945
2,undef,4.400259,3.976295,4.021928,3.670448,4.81914,2.987886,4.465547,3.508204,3.057743,...,4.147903,1.208198,0.911905,1.829139,2.997120,6.606668,8.807279,2.899934,2.876148,5.454271

In [1]:
fig = px.pie(Domain_group, names="Domain", values= 'Percent', color= 'Domain')
fig.show()

NameError: name 'px' is not defined

### Highest abundance Phylum?

In [4]:
Domain_Phylum= taxonomy.groupby(['Domain', 'Phylum']).agg(['sum'])
Domain_Phylum['Percent']= Domain_Phylum.sum(axis=1, numeric_only=True) / 139
Domain_Phylum.sort_values(by=['Percent'], inplace=True, ascending=False)
Domain_Phylum.reset_index(inplace=True)
Domain_Phylum.head()

,Domain,Phylum,Class,Order,Family,Genus,OTU.rep,TARA_018_DCM_0.22-1.6,TARA_018_SRF_0.22-1.6,TARA_023_DCM_0.22-1.6,...,TARA_085_SRF_0.22-3,TARA_093_DCM_0.22-3,TARA_093_SRF_0.22-3,TARA_094_SRF_0.22-3,TARA_096_SRF_0.22-3,TARA_098_DCM_0.22-3,TARA_098_MES_0.22-3,TARA_098_SRF_0.22-3,TARA_099_SRF_0.22-3,Percent
,,,sum,sum,sum,sum,sum,sum,sum,sum,...,sum,sum,sum,sum,sum,sum,sum,sum,sum,
0,Bacteria,Proteobacteria,GammaproteobacteriaGammaproteobacteriaGammapro...,EnterobacterialesB38EnterobacterialesAlteromon...,EnterobacteriaceaeGammaproteobacteria(undef)En...,EnterobacterGammaproteobacteria(undef)Enteroba...,AAAA02020713.1.1297AAAA02020732.66.1490AAAA020...,61.645892,65.908173,74.076935,...,66.193671,83.752869,77.897795,76.443471,78.651004,57.125832,48.153826,74.946067,68.842254,60.042228
1,Bacteria,Cyanobacteria,ChloroplastCyanobacteriaChloroplastCyanobacter...,Chloroplast(undef)SubsectionIChloroplast(undef...,Chloroplast(undef)FamilyIChloroplast(undef)Fam...,Chloroplast(undef)SynechococcusChloroplast(und...,AACY020080403.492.1950AANO01000009.1.2054AB027...,13.142980,11.354963,7.337427,...,9.592868,1.800232,9.078673,6.922084,7.319551,17.968001,0.265801,10.250028,14.801282,11.102198
2,Bacteria,Bacteroidetes,SphingobacteriiaFlavobacteriaFlavobacteriaFlav...,SphingobacterialesFlavobacterialesFlavobacteri...,ChitinophagaceaeCryomorphaceaeFlavobacteriacea...,unculturedOwenweeksiaNS5 marine groupCroceital...,AACY020170354.109.1617AACY020259437.2024.3522A...,7.518654,6.262253,3.660237,...,19.666085,11.089899,10.485228,8.622862,6.396292,3.894414,1.221491,5.557860,7.112818,5.864605
3,undef,undef,undef,undef,undef,undef,unclassified,4.400259,3.976295,4.021928,...,4.147903,1.208198,0.911905,1.829139,2.997120,6.606668,8.807279,2.899934,2.876148,5.454271
4,Bacteria,Deferribacteres,DeferribacteresDeferribacteresDeferribacteresD...,DeferribacteralesDeferribacteralesDeferribacte...,SAR406 clade(Marine group A)SAR406 clade(Marin...,Deferribacteres(undef)Deferribacteres(undef)De...,AACY020207233.1273.2814AACY020518560.687.2227A...,4.373517,3.899972,1.256499,...,0.196673,0.124949,0.204141,2.447462,0.812146,4.971097,10.285612,1.821274,1.772740,4.730395

In [2]:
fig1 = px.bar(Domain_Phylum, x="Domain", y= 'Percent', color= 'Phylum', text_auto=True)
fig1.show()

NameError: name 'px' is not defined

### Abundance break-down by taxonomy hierarchy upto Genus level

In [5]:
Taxonomy_groups= taxonomy.groupby(['Domain', 'Phylum', 'Class', 'Order', 'Family', 'Genus']).agg(['sum'])
Taxonomy_groups['Percent']= Taxonomy_groups.sum(axis=1, numeric_only=True) / 139
Taxonomy_groups.sort_values(by=['Percent'], inplace=True, ascending=False)
Taxonomy_groups.reset_index(inplace=True)
Taxonomy_groups.head()

,Domain,Phylum,Class,Order,Family,Genus,OTU.rep,TARA_018_DCM_0.22-1.6,TARA_018_SRF_0.22-1.6,TARA_023_DCM_0.22-1.6,...,TARA_085_SRF_0.22-3,TARA_093_DCM_0.22-3,TARA_093_SRF_0.22-3,TARA_094_SRF_0.22-3,TARA_096_SRF_0.22-3,TARA_098_DCM_0.22-3,TARA_098_MES_0.22-3,TARA_098_SRF_0.22-3,TARA_099_SRF_0.22-3,Percent
,,,,,,,sum,sum,sum,sum,...,sum,sum,sum,sum,sum,sum,sum,sum,sum,
0,Bacteria,Proteobacteria,Alphaproteobacteria,SAR11 clade,Surface 1,Alphaproteobacteria(undef),AB176372.1.1371AB193916.1.1438AB193924.1.1441A...,16.200992,19.047156,16.180017,...,18.508716,10.730067,16.214640,20.716159,21.533941,16.742007,7.805796,20.565051,18.128162,14.610507
1,Bacteria,Proteobacteria,Alphaproteobacteria,SAR11 clade,Alphaproteobacteria(undef),Alphaproteobacteria(undef),AACY020095396.2822.4287AACY020468607.261.1725A...,6.955359,8.061837,6.875895,...,3.480685,3.055085,4.655989,8.072633,8.517668,9.642202,2.180167,9.590386,9.121854,6.229565
2,Bacteria,Proteobacteria,Gammaproteobacteria,Oceanospirillales,SAR86 clade,Gammaproteobacteria(undef),AACY020255495.903.2404AACY020393406.361.1862AA...,10.005607,9.013633,14.335770,...,3.841559,3.265836,4.436144,9.627050,18.145733,4.154681,2.044778,14.960173,12.399808,5.894725
3,undef,undef,undef,undef,undef,undef,unclassified,4.400259,3.976295,4.021928,...,4.147903,1.208198,0.911905,1.829139,2.997120,6.606668,8.807279,2.899934,2.876148,5.454271
4,Bacteria,Cyanobacteria,Cyanobacteria,SubsectionI,FamilyI,Prochlorococcus,AF115271.1.1404AY664072.1.1205AY664087.1.1207E...,11.056286,9.556128,3.549092,...,0.027571,0.351252,1.597236,4.814308,5.418208,13.220186,0.081632,7.659863,11.726313,5.208997

In [3]:
fig2 = px.sunburst(Taxonomy_groups, path=['Domain', 'Phylum', 'Class', 'Order', 'Family', 'Genus'], values='Percent', color= 'Genus')
fig2.show()

NameError: name 'px' is not defined

## Region-wise Abundance

In [7]:
# Transposing The Genus Pivot Table
Genus= pd.read_csv('C:/Users/Aditi Sony/Downloads/Complex Data Visualisation/Summative Assignment/Data/PivotedTaxonomy/Tara_GenusTable.csv')
Genus= Genus.transpose()
Genus.columns = Genus.iloc[0]
Genus.drop(Genus.index[[0]], inplace=True)
Genus.reset_index(inplace=True)
Genus = Genus.rename(columns = {'index':'SampleID'})
Genus.head()

Genus,SampleID,(undef),028H05-P-BN-P5(undef),060F05-B-SD-P93,12up,4C0d-2(undef),AB64A-17(undef),Abiotrophia,Acanthopleuribacter,Acaryochloris,...,Zhangella,Zhihengliuella,Zhouia,Zimmermannella,Zobellella,Zobellia,Zoogloea,Zunongwangia,Zymobacter,Zymomonas
0,TARA_018_DCM_0.22-1.6,0.010352,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.000863,0.003451,0.0,0.0
1,TARA_018_SRF_0.22-1.6,0.005986,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001497,0.0,0.0
2,TARA_023_DCM_0.22-1.6,0.009419,0.0,0.0,0.0,0.0,0.0,0.001884,0.0,0.001884,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001884,0.0,0.0
3,TARA_023_SRF_0.22-1.6,0.011085,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001232,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,TARA_025_DCM_0.22-1.6,0.009285,0.0,0.0,0.001032,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001032,0.0,0.0

In [8]:
# Reading Metadata file
Metadata= pd.read_csv('C:/Users/Aditi Sony/Downloads/Complex Data Visualisation/Summative Assignment/Data/Tara_SampleMeta.csv')
Metadata.head()

,SampleID,Year,Month,Layer of Origin,MarinePelagicBiomes,OceanAndSeaRegions,MarinePelagicProvince
0,TARA_004_DCM_0.22-1.6,2009,9,DCM,Westerlies Biome,North Atlantic Ocean,North Atlantic Subtropical Gyral Province
1,TARA_004_SRF_0.22-1.6,2009,9,SRF,Westerlies Biome,North Atlantic Ocean,North Atlantic Subtropical Gyral Province
2,TARA_007_DCM_0.22-1.6,2009,9,DCM,Westerlies Biome,Mediterranean Sea,"Mediterranean Sea, Black Sea Province"
3,TARA_007_SRF_0.22-1.6,2009,9,SRF,Westerlies Biome,Mediterranean Sea,"Mediterranean Sea, Black Sea Province"
4,TARA_009_DCM_0.22-1.6,2009,9,DCM,Westerlies Biome,Mediterranean Sea,"Mediterranean Sea, Black Sea Province"

In [11]:
# Joining Genus and Metadata files
Genus_Meta= pd.merge(Genus, Metadata, how= "outer", on=['SampleID', 'SampleID'])
Genus_Meta.shape

(139, 1603)

In [13]:
Genus_Meta.head()

,SampleID,(undef),028H05-P-BN-P5(undef),060F05-B-SD-P93,12up,4C0d-2(undef),AB64A-17(undef),Abiotrophia,Acanthopleuribacter,Acaryochloris,...,Zoogloea,Zunongwangia,Zymobacter,Zymomonas,Year,Month,Layer of Origin,MarinePelagicBiomes,OceanAndSeaRegions,MarinePelagicProvince
0,TARA_018_DCM_0.22-1.6,0.010352,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000863,0.003451,0.0,0.0,2009.0,11.0,DCM,Westerlies Biome,Mediterranean Sea,"Mediterranean Sea, Black Sea Province"
1,TARA_018_SRF_0.22-1.6,0.005986,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.001497,0.0,0.0,2009.0,11.0,SRF,Westerlies Biome,Mediterranean Sea,"Mediterranean Sea, Black Sea Province"
2,TARA_023_DCM_0.22-1.6,0.009419,0.0,0.0,0.0,0.0,0.0,0.001884,0.0,0.001884,...,0.0,0.001884,0.0,0.0,2009.0,11.0,DCM,Westerlies Biome,Mediterranean Sea,"Mediterranean Sea, Black Sea Province"
3,TARA_023_SRF_0.22-1.6,0.011085,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001232,...,0.0,0.0,0.0,0.0,2009.0,11.0,SRF,Westerlies Biome,Mediterranean Sea,"Mediterranean Sea, Black Sea Province"
4,TARA_025_DCM_0.22-1.6,0.009285,0.0,0.0,0.001032,0.0,0.0,0.0,0.0,0.0,...,0.0,0.001032,0.0,0.0,2009.0,11.0,DCM,Westerlies Biome,Mediterranean Sea,"Mediterranean Sea, Black Sea Province"

In [16]:
Genus_Meta.nunique()

SampleID                 139
(undef)                  139
028H05-P-BN-P5(undef)     20
060F05-B-SD-P93           15
12up                      14
                        ...
Month                     12
Layer of Origin            3
MarinePelagicBiomes        4
OceanAndSeaRegions         8
MarinePelagicProvince     19
Length: 1603, dtype: int64

### Parallel Coordinate Sets Plot

In [4]:
fig3 = px.parallel_categories(Genus_Meta, dimensions=['Layer of Origin', 'MarinePelagicBiomes', 'OceanAndSeaRegions', 'MarinePelagicProvince'])
fig3.show()

NameError: name 'px' is not defined

### Depth-wise Abundance

In [19]:
Depth_group= Genus_Meta.drop(['Year', 'Month', 'SampleID'], axis=1)
Depth_group= Depth_group.groupby(['Layer of Origin']).sum()
Depth_group= Depth_group.transpose()
Depth_group.reset_index(inplace=True)
Depth_group = Depth_group.rename(columns = {'index':'Genus'})
Depth_group.head()

Layer of Origin                  Genus       DCM       MES       SRF
0                              (undef)  2.144981  7.111298  1.328858
1                028H05-P-BN-P5(undef)  0.005235  0.059899  0.001041
2                      060F05-B-SD-P93  0.004281   0.00584  0.004236
3                                 12up  0.003542  0.002084  0.006945
4                        4C0d-2(undef)  0.002977  0.005815   0.00377

In [5]:
Depth_melt = Depth_group.melt(id_vars='Genus')
fig4 = px.bar(Depth_melt, x="value", y="Layer of Origin", color='Genus', orientation='h')
fig4.show()

NameError: name 'Depth_group' is not defined

### Marine Pelagic Biome-wise Abundance

In [21]:
Biome_group= Genus_Meta.drop(['Year', 'Month', 'SampleID'], axis=1)
Biome_group= Biome_group.groupby(['MarinePelagicBiomes']).sum()
Biome_group= Biome_group.transpose()
Biome_group.reset_index(inplace=True)
Biome_group = Biome_group.rename(columns = {'index':'Genus'})
Biome_group.head()

MarinePelagicBiomes,Genus,Coastal Biome,Polar Biome,Trades Biome,Westerlies Biome
0,(undef),2.258911,0.090833,6.317543,1.91785
1,028H05-P-BN-P5(undef),0.013063,0.021944,0.017701,0.013468
2,060F05-B-SD-P93,0.001633,0.001097,0.00755,0.004077
3,12up,0.004141,0.0,0.005645,0.002785
4,4C0d-2(undef),0.005529,0.0,0.005089,0.001944

In [6]:
Biome_melt = Biome_group.melt(id_vars='Genus')
fig5 = px.bar(Biome_melt, x="value", y="MarinePelagicBiomes", color='Genus', orientation='h')
fig5.show()

NameError: name 'Biome_group' is not defined

### Ocean-wise Abundance

In [23]:
Ocean_group= Genus_Meta.drop(['Year', 'Month', 'SampleID'], axis=1)
Ocean_group= Ocean_group.groupby(['OceanAndSeaRegions']).sum()
Ocean_group= Ocean_group.transpose()
Ocean_group.reset_index(inplace=True)
Ocean_group = Ocean_group.rename(columns = {'index':'Genus'})
Ocean_group.head()

OceanAndSeaRegions,Genus,Indian Ocean,Mediterranean Sea,North Atlantic Ocean,North Pacific Ocean,Red Sea,South Atlantic Ocean,South Pacific Ocean,Southern Ocean
0,(undef),2.752301,0.12495,1.522807,2.580103,0.14438,1.896866,1.472898,0.090833
1,028H05-P-BN-P5(undef),0.006717,0.0,0.007813,0.017144,0.0,0.007049,0.005509,0.021944
2,060F05-B-SD-P93,0.001565,0.0,0.004077,0.0,0.000786,0.002335,0.004497,0.001097
3,12up,0.000987,0.001032,0.001295,0.001753,0.002309,0.0,0.005195,0.0
4,4C0d-2(undef),0.006318,0.0,0.003742,0.0,0.0,0.0,0.002501,0.0

In [7]:
Ocean_melt = Ocean_group.melt(id_vars='Genus')
fig6 = px.bar(Ocean_melt, x="value", y="OceanAndSeaRegions", color='Genus', orientation='h')
fig6.show()

NameError: name 'Ocean_group' is not defined

### Province-wise Abundance

In [25]:
Province_group= Genus_Meta.drop(['Year', 'Month', 'SampleID'], axis=1)
Province_group= Province_group.groupby(['MarinePelagicProvince']).sum()
Province_group= Province_group.transpose()
Province_group.reset_index(inplace=True)
Province_group = Province_group.rename(columns = {'index':'Genus'})
Province_group.head()

MarinePelagicProvince,Genus,Antarctic Province,Benguela Current Coastal Province,Caribbean Province,Chile-Peru Current Coastal Province,Eastern Africa Coastal Province,Guianas Coastal Province,Gulf Stream Province,Indian Monsoon Gyres Province,Indian South Subtropical Gyre Province,"Mediterranean Sea, Black Sea Province",North Atlantic Subtropical Gyral Province,North Pacific Equatorial Countercurrent Province,North Pacific Subtropical and Polar Front Provinces,Northwest Arabian Sea Upwelling Province,Pacific Equatorial Divergence Province,"Red Sea, Persian Gulf Province",South Atlantic Gyral Province,"South Pacific Subtropical Gyre Province, North and South",Southwest Atlantic Shelves Province
0,(undef),0.090833,0.130931,0.332466,0.064295,0.976817,0.063462,0.342743,1.072312,0.169572,0.12495,0.784135,1.774323,0.666022,0.5336,0.13284,0.14438,1.841943,1.326553,0.012959
1,028H05-P-BN-P5(undef),0.021944,0.0,0.000899,0.005447,0.006717,0.0,0.005085,0.0,0.0,0.0,0.001829,0.005143,0.006554,0.0,0.001772,0.0,0.007049,0.003738,0.0
2,060F05-B-SD-P93,0.001097,0.0,0.0,0.0,0.000847,0.0,0.002034,0.0,0.000718,0.0,0.002043,0.0,0.0,0.0,0.000973,0.000786,0.002335,0.003524,0.0
3,12up,0.0,0.0,0.0,0.000536,0.0,0.001295,0.0,0.000987,0.0,0.001032,0.0,0.0,0.001753,0.0,0.00089,0.002309,0.0,0.003768,0.0
4,4C0d-2(undef),0.0,0.0,0.001798,0.0,0.003731,0.0,0.0,0.002588,0.0,0.0,0.001944,0.0,0.0,0.0,0.00089,0.0,0.0,0.001611,0.0

In [8]:
Province_melt = Province_group.melt(id_vars='Genus')
fig7 = px.bar(Province_melt, x="value", y="MarinePelagicProvince", color='Genus', orientation='h')
fig7.show()

NameError: name 'Province_group' is not defined

### Sample-wise Abundance

In [27]:
Sample_group= Genus_Meta.drop(['Year', 'Month', 'Layer of Origin', 'MarinePelagicBiomes', 'OceanAndSeaRegions', 'MarinePelagicProvince'], axis=1)
Sample_group= Sample_group.transpose()
Sample_group.columns = Sample_group.iloc[0]
Sample_group.drop(Sample_group.index[[0]], inplace=True)
Sample_group.reset_index(inplace=True)
Sample_group = Sample_group.rename(columns = {'index':'Genus'})
Sample_group.head()

SampleID,Genus,TARA_018_DCM_0.22-1.6,TARA_018_SRF_0.22-1.6,TARA_023_DCM_0.22-1.6,TARA_023_SRF_0.22-1.6,TARA_025_DCM_0.22-1.6,TARA_025_SRF_0.22-1.6,TARA_030_DCM_0.22-1.6,TARA_030_SRF_0.22-1.6,TARA_031_SRF_0.22-1.6,...,TARA_085_MES_0.22-3,TARA_085_SRF_0.22-3,TARA_093_DCM_0.22-3,TARA_093_SRF_0.22-3,TARA_094_SRF_0.22-3,TARA_096_SRF_0.22-3,TARA_098_DCM_0.22-3,TARA_098_MES_0.22-3,TARA_098_SRF_0.22-3,TARA_099_SRF_0.22-3
0,(undef),0.010352,0.005986,0.009419,0.011085,0.009285,0.009757,0.007602,0.020901,0.029702,...,0.073511,0.004289,0.011262,0.002243,0.009392,0.008772,0.052053,0.047784,0.00968,0.018737
1,028H05-P-BN-P5(undef),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.021944,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001041
2,060F05-B-SD-P93,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.001097,0.0,0.0,0.0,0.0,0.001462,0.0,0.000996,0.0,0.0
3,12up,0.0,0.0,0.0,0.0,0.001032,0.0,0.0,0.0,0.0,...,0.0,0.0,0.000536,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4C0d-2(undef),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
Sample_melt = Sample_group.melt(id_vars='Genus')
Sample_melt.head()

                   Genus               SampleID     value
0                (undef)  TARA_018_DCM_0.22-1.6  0.010352
1  028H05-P-BN-P5(undef)  TARA_018_DCM_0.22-1.6       0.0
2        060F05-B-SD-P93  TARA_018_DCM_0.22-1.6       0.0
3                   12up  TARA_018_DCM_0.22-1.6       0.0
4          4C0d-2(undef)  TARA_018_DCM_0.22-1.6       0.0

In [9]:
fig8= px.line(Sample_melt, x="Genus", y="value", color= "SampleID")
fig8.show()

NameError: name 'px' is not defined

### Sample to Region mapping

In [34]:
Sample_mapping= Genus_Meta.drop(['Year', 'Month'], axis=1)
Sample_mapping= Sample_mapping.groupby(['Layer of Origin', 'MarinePelagicBiomes', 'OceanAndSeaRegions', 'MarinePelagicProvince', 'SampleID']).sum()
Sample_mapping= Sample_mapping.transpose()
Sample_mapping.reset_index(inplace=True)
Sample_mapping = Sample_mapping.rename(columns = {'index':'Genus'})
Sample_mapping.head()

Layer of Origin                        Genus                             DCM  \
MarinePelagicBiomes                                           Coastal Biome
OceanAndSeaRegions                                              Indian Ocean
MarinePelagicProvince                        Eastern Africa Coastal Province
SampleID                                                 TARA_058_DCM_0.22-3
0                                    (undef)                        0.069219
1                      028H05-P-BN-P5(undef)                        0.000000
2                            060F05-B-SD-P93                        0.000000
3                                       12up                        0.000000
4                              4C0d-2(undef)                        0.000000

Layer of Origin                                                \
MarinePelagicBiomes
OceanAndSeaRegions
MarinePelagicProvince
SampleID              TARA_064_DCM_0.22-3 TARA_065_DCM_0.22-3
0                                0.009917            0.041855
1                                0.000000            0.000000
2                                0.000000            0.000000
3                                0.000000            0.000000
4                                0.000000            0.000000

Layer of Origin                                                 \
MarinePelagicBiomes
OceanAndSeaRegions
MarinePelagicProvince Northwest Arabian Sea Upwelling Province
SampleID                                 TARA_036_DCM_0.22-1.6
0                                                     0.018968
1                                                     0.000000
2                                                     0.000000
3                                                     0.000000
4                                                     0.000000

Layer of Origin                             \
MarinePelagicBiomes
OceanAndSeaRegions    North Atlantic Ocean
MarinePelagicProvince   Caribbean Province
SampleID               TARA_142_DCM_0.22-3
0                                 0.082627
1                                 0.000000
2                                 0.000000
3                                 0.000000
4                                 0.000000

Layer of Origin                                            \
MarinePelagicBiomes
OceanAndSeaRegions                    North Pacific Ocean
MarinePelagicProvince Chile-Peru Current Coastal Province
SampleID                              TARA_109_DCM_0.22-3
0                                                0.011648
1                                                0.000000
2                                                0.000000
3                                                0.000000
4                                                0.000000

Layer of Origin                                                             \
MarinePelagicBiomes
OceanAndSeaRegions                           Red Sea
MarinePelagicProvince Red Sea, Persian Gulf Province
SampleID                       TARA_032_DCM_0.22-1.6 TARA_034_DCM_0.22-1.6
0                                           0.015715              0.059219
1                                           0.000000              0.000000
2                                           0.000786              0.000000
3                                           0.000000              0.000000
4                                           0.000000              0.000000

Layer of Origin                                          ...  \
MarinePelagicBiomes                                      ...
OceanAndSeaRegions                 South Atlantic Ocean  ...
MarinePelagicProvince Benguela Current Coastal Province  ...
SampleID                            TARA_066_DCM_0.22-3  ...
0                                              0.012687  ...
1                                              0.000000  ...
2                                              0.000000  ...
3                                              0.000000  ...
4                                              0.000000  ...

Layer of Origin                        SRF  \
MarinePelagicBiomes       Westerlies Biome
OceanAndSeaRegions    North Atlantic Ocean
MarinePelagicProvince Gulf Stream Province
SampleID               TARA_145_SRF_0.22-3
0                                 0.021399
1                                 0.000000
2                                 0.000000
3                                 0.000000
4                                 0.000000

Layer of Origin                                                  \
MarinePelagicBiomes
OceanAndSeaRegions
MarinePelagicProvince North Atlantic Subtropical Gyral Province
SampleID                                  TARA_004_SRF_0.22-1.6
0                                                      0.004390
1                                                      0.000000
2                                                      0.000000
3                                                      0.000000
4                                                      0.001097

Layer of Origin                                                \
MarinePelagicBiomes
OceanAndSeaRegions
MarinePelagicProvince
SampleID              TARA_146_SRF_0.22-3 TARA_148_SRF_0.22-3
0                                0.016917            0.009318
1                                0.000000            0.000000
2                                0.000000            0.000000
3                                0.000000            0.000000
4                                0.000000            0.000847

Layer of Origin                                                \
MarinePelagicBiomes
OceanAndSeaRegions
MarinePelagicProvince
SampleID              TARA_149_SRF_0.22-3 TARA_150_SRF_0.22-3
0                                0.015785            0.008087
1                                0.000000            0.000000
2                                0.000000            0.000000
3                                0.000000            0.000000
4                                0.000000            0.000000

Layer of Origin                                                \
MarinePelagicBiomes
OceanAndSeaRegions
MarinePelagicProvince
SampleID              TARA_151_SRF_0.22-3 TARA_152_SRF_0.22-3
0                                0.008135            0.033579
1                                0.000000            0.000000
2                                0.000000            0.001083
3                                0.000000            0.000000
4                                0.000000            0.000000

Layer of Origin                                                            \
MarinePelagicBiomes
OceanAndSeaRegions                                    North Pacific Ocean
MarinePelagicProvince North Pacific Subtropical and Polar Front Provinces
SampleID                                              TARA_132_SRF_0.22-3
0                                                               0.007532
1                                                               0.000000
2                                                               0.000000
3                                                               0.000000
4                                                               0.000000

Layer of Origin
MarinePelagicBiomes
OceanAndSeaRegions
MarinePelagicProvince
SampleID              TARA_133_SRF_0.22-3
0                                0.035474
1                                0.000000
2                                0.000000
3                                0.000669
4                                0.000000

[5 rows x 136 columns]

In [35]:
Sample_melt = Sample_mapping.melt(id_vars='Genus')
Sample_melt.head()

,Genus,Layer of Origin,MarinePelagicBiomes,OceanAndSeaRegions,MarinePelagicProvince,SampleID,value
0,(undef),DCM,Coastal Biome,Indian Ocean,Eastern Africa Coastal Province,TARA_058_DCM_0.22-3,0.069219
1,028H05-P-BN-P5(undef),DCM,Coastal Biome,Indian Ocean,Eastern Africa Coastal Province,TARA_058_DCM_0.22-3,0.000000
2,060F05-B-SD-P93,DCM,Coastal Biome,Indian Ocean,Eastern Africa Coastal Province,TARA_058_DCM_0.22-3,0.000000
3,12up,DCM,Coastal Biome,Indian Ocean,Eastern Africa Coastal Province,TARA_058_DCM_0.22-3,0.000000
4,4C0d-2(undef),DCM,Coastal Biome,Indian Ocean,Eastern Africa Coastal Province,TARA_058_DCM_0.22-3,0.000000

In [10]:
fig10 = px.treemap(Sample_melt, path=['Layer of Origin', 'MarinePelagicBiomes', 'OceanAndSeaRegions', 'MarinePelagicProvince', 'SampleID'], values='value', color= 'Layer of Origin')
fig10.show()

NameError: name 'px' is not defined

## Coordinated Multiple views

In [9]:
app = dash.Dash(__name__)

app.layout = html.Div([
    html.H1(children='TARA Ocean Microbiome Analysis'),
    dcc.Graph(id='Overview-graph', figure=fig2),
    dcc.Dropdown(id='Domain-selector',
                 options= taxonomy['Domain'].unique()
                ),
    dcc.Graph(id='Phylum-graph'),
    dcc.Dropdown(id='Phylum-selector',
                 options= taxonomy['Phylum'].unique()
                ),
    dcc.Graph(id='Sample-graph')
    
])

@app.callback(
    dash.dependencies.Output('Phylum-graph', 'figure'), 
    [dash.dependencies.Input('Domain-selector', 'value')])

def update_graph1(Domain):
    dff= taxonomy[taxonomy['Domain']== Domain]
    Domain_Phylum= dff.groupby(['Domain', 'Phylum']).agg(['sum'])
    Domain_Phylum['Percent']= Domain_Phylum.sum(axis=1, numeric_only=True) / 139
    Domain_Phylum.sort_values(by=['Percent'], inplace=True, ascending=False)
    Domain_Phylum.reset_index(inplace=True)
    Fig1 = px.bar(Domain_Phylum, x="Domain", y= 'Percent', color= 'Phylum', text_auto=True)
    return Fig1       


@app.callback(
    dash.dependencies.Output('Sample-graph', 'figure'), 
    [dash.dependencies.Input('Phylum-selector', 'value')])

def update_graph2(Phylum):
    dff= taxonomy[taxonomy['Phylum']== Phylum]
    Sample= dff.drop(['Domain', 'Class', 'Order', 'Family', 'Genus', 'OTU.rep'], axis=1)
    Sample= Sample.groupby(['Phylum']).sum()
    Sample= Sample.transpose()
    Sample.reset_index(inplace=True)
    Sample = Sample.rename(columns = {'index':'SampleID'})
    Fig2 = px.line(Sample, x= 'SampleID', y= Sample.columns )
    return Fig2

In [11]:
app.run_server()

NameError: name 'app' is not defined